name: Vessell
favicon: null
layout_spectrum: 0.7344376251567155
typography_spectrum: 0.12119356961920857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040000'
    - '#612d05'
    - '#cc6e17'
    - '#fefaba'
    - '#faa721'
  brandStrength: 0.17306626169010997
  lightness: 0.3986448037903756
  saturation: 0.4522513230331242
  rhythmicContrast: 0.9966955510899425
purpose: []
